# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a921e96f685d56098ea364e1ad08c5e28df2f1597218e4dee04a3e2bbd03a5006ca3a49a0d27e3389c1ac8718df1047188abf2f58d1e3471b846f4f617f9f727

test:
  secret_key_base: 5042dfc02a8aaae00bda19e2074b6b5fa37bf7f060dccc9a4a446f0ea4398ff064ccd971b19ae2744d14c54172463e6283d75a2f1eee73d38fd03663286ecbc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
